### ISSUE TITLE
Error installing decanter

### ISSUE THREAD

**Issue by AleffSouza** [gengo/decanter#86]
Using python 3.4.3 version I got this when I tried install it:

Collecting gevent==0.13.8 (from decanter)
  Using cached gevent-0.13.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/89/7wmscwnd4fv88087nfzb_rm40000gp/T/pip-build-idv6f45e/gevent/setup.py", line 95
        print 'Linking %s to %s' % (path_to_build_core_so, path_to_core_so)
                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/89/7wmscwnd4fv88087nfzb_rm40000gp/T/pip-build-idv6f45e/gevent

**Comment by kelvintaywl** [comment]
Hi @AleffSouza,

the above error is due to Python 3's syntax for print statements. Specifically, in python 3.x, we would need to use `print()` function instead of the `print` syntax [see notes here](https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function)

If I am not wrong, the codebase for Decanter has been made for python 2.x in mind, not python 3.x . Perhaps, you may wish to fork this repository and update the codebase to make it python 3.x ready instead? :bow:
